### ISSUE TITLE
rpt spam caused by in fn_insertVehicle.sqf (and fn_vehicleStore)

### ISSUE THREAD

**Issue by Nesias** [ArmaLife/Altis#379] opened 2016-03-04 15:26 UTC
_**This Error is observed with release 4.4r1 but should still be present.**_
When you buy a vehicle and it got created, fn_insertVehicle will insert an emtpy Array into the gear column of vehicles table. Which will persist even if you store the vehicle in garage (if gear saving in vehicle is disabled).

This will result in an server.rpt spam every time someone retrieves a vehicle from garage.
This is caused by the fact that the column enty will be read as type ARRAY and not STRING.
Which will cause line 72 of [fn_spawnVehicle](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/Systems/fn_spawnVehicle.sqf#L72) to create an error message. 
(The Error will point towards fn_mrestoArray.sqf but that one isn't the problem).

That error message will popup in server.rpt as long as you don't allow gear saving in vehicles.
If you allow gear saving, that empty array will be replaced with `"[[[],[]],[[],[]],[[],[]],[[],[]]]"` (**if no gear is to be stored**) when you store a vehicle and the spaming will stop (at least for this vehicle).

**How to fix?** 
Just change the INSERT Query in [fn_inserVehicle](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/MySQL/fn_insertVehicle.sqf#L21) so that the same array as shown above is inserted. Also [fn_vehicleStore](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/Systems/fn_vehicleStore.sqf#L82) has to be changed (at line 82). 
To fix an already existing DB you could use this SQL code:
 `UPDATE vehicles SET gear='"[[[],[]],[[],[]],[[],[]],[[],[]]]"' where gear ='[]';`. 
**(Check if table and column names are correct!)**

**Comment by Liam0** [comment] 2016-03-04 15:37
Hey @Nesias would you please check it with https://github.com/ArmaLife/Altis/pull/376

**Comment by Nesias** [comment] 2016-03-04 15:54
@Liam0 even with #376 that the error cause is still present. 

[fn_insertVehicle line 23](https://github.com/ArmaLife/Altis/pull/376/files?diff=unified#diff-7c40f91062ef63878e0ec8a672171d07R23) should be: 
`_query = format["INSERT INTO vehicles (side, classname, type, pid, alive, active, inventory, color, plate, gear, damage) VALUES ('%1', '%2', '%3', '%4', '1','1','""[[],0]""', '%5', '%6','""[[[],[]],[[],[]],[[],[]],[[],[]]]""','""[]""')",_side,_className,_type,_uid,_color,_plate];` 

[fn_fn_vehicleStore line 103](https://github.com/ArmaLife/Altis/pull/376/files?diff=unified#diff-23b8497b366cbf90ee80815a89c8a979R103) should be:
`_cargo = [[[],[]],[[],[]],[[],[]],[[],[]]];`

(I hope thats what you wanted ^^")

**Comment by Liam0** [comment] 2016-03-04 15:55
It should never be set to "[[[],[]],[[],[]],[[],[]],[[],[]]]" which error are you referring to

**Comment by Nesias** [comment] 2016-03-04 16:04
What im referring to is that you will get an error message as long as you don't allow gear saving for vehicles (arma gear not virtual) caused by an empty array in vehicles table (column gear) becaused that array will be retrieved as array (and not as string).

If you store a vehicle with gear saving (vehicles) enabled and there is no gear in that vehicle you will find  "[[[],[]],[[],[]],[[],[]],[[],[]]]" in the column gear (DB), wich will be read as string and won't cause an error.

**Comment by Liam0** [comment] 2016-03-04 16:37
Post rpt please 

this is not the only place we use "[]" as default strings in the database for arrays basically anywhere we save array's to the database we do the exact same thing without problems.

When we pull it out of the database it woulden't make a difference saving it as "[[[],[]],[[],[]],[[],[]],[[],[]]]" or "[]"  unless when we actually need to use it.

Also you shoulden't even be having "[[[],[]],[[],[]],[[],[]],[[],[]]]" in the database with the latest commits and the pull request from last night.

Having empty array like that is completely pointless and if what you describe is infact a problem then what you're saying is not be the cause or solution.

**Comment by Nesias** [comment] 2016-03-04 17:23
relevant part of rpt: 
--
2016/03/04, 15:38:58 "------------- Client Query Request -------------"
2016/03/04, 15:38:58 "QUERY: SELECT id, side, classname, type, pid, alive, active, plate, color, inventory, gear, fuel FROM vehicles WHERE id='2' AND pid='76561197977300507'"
2016/03/04, 15:38:58 "Time to complete: 0 (in seconds)"
2016/03/04, 15:38:58 "Result: [2,"civ","C_Offroad_01_F","Car","76561197977300507",1,0,418497,5,"[[],0]",[],1]"
2016/03/04, 15:38:58 "------------------------------------------------"
2016/03/04, 15:38:58 Error in expression <f"









private["_array"];
_array = param [0,"",[""]];
if(_array == "") exit>
2016/03/04, 15:38:58   Error position: <param [0,"",[""]];
if(_array == "") exit>
2016/03/04, 15:38:58   Error Type Array, expected String
2016/03/04, 15:38:58 File life_server\Functions\MySQL\fn_mresToArray.sqf, line 11

--
Yes the error message is pointing towards fn_mresToArray, where i replaced bis_fnc_param with param (which i hopefully don't have to justify), and yes this is actually one part of the cause. 

Param will acts as bis_fnc_param with one difference, it will inform "you" that it got data of a type that isn't expected (-> error message in rpt). (And yes i know that i forgot to mention this change in my first comment)

While you could ignore my issue now (considering bis_fnc_param is still used at your side), the changes i suggested should atleast increase consistency of the vehicles table (no difference between settings).

**Comment by Liam0** [comment] 2016-03-04 17:58
i'll check it out later. but if u use the latest changes u shoulden't have any problems with database consistency.

**Comment by Liam0** [comment] 2016-03-04 19:21
i've just tried to change "spawnvehicle, vehicleCreate,vehicleStore,vehicleUpdate" to use params but i can't replicate this error im afraid.

**Comment by Nesias** [comment] 2016-03-04 22:07
did you set save vehicle gear to false ?

**Comment by Liam0** [comment] 2016-03-04 22:17
i tried with everything false and everything true

**Comment by Nesias** [comment] 2016-03-04 22:20
did you changed fn_mrestoArray to?

**Comment by Liam0** [comment] 2016-03-04 22:29
Yeah just tried. still not getting any errors i can send you the file's if u want. just throw me a message on gitter but closing this for now.

**Closed by Liam0** 2016-03-04 22:29 UTC

**Comment by Nesias** [comment] 2016-03-04 22:40
okay thats random.. o.O will try with different server on my side first, but thanks (maybe keep something like this in mind when you change from fnc_param to param )
