### ISSUE TITLE
another situation where someone got nulled.

### ISSUE THREAD

**Issue by 9mmfullclip** [ArmaLife/Altis#537] opened 2016-04-14 13:11 UTC
14:57:14 Error in expression <t pushBack [_uid, _new];
};
_new = _new select 2;
[_uid, _new] call TON_fnc_setP>
14:57:14   Error position: <select 2;
[_uid, _new] call TON_fnc_setP>
14:57:14   Error Zero divisor
14:57:14 File life_server\Functions\MySQL\fn_queryRequest.sqf, line 127

**Comment by 9mmfullclip** [comment] 2016-04-14 13:23
we have disabled playtime now until this thing gets sorted out.

**Comment by Heavybob** [comment] 2016-04-14 13:41
disabled playtime?

**Comment by DardoTheMaster** [comment] 2016-04-14 14:33
Your infos are not enough, As i'm unable to reproduce the issue ,could you please tell us when this issue occurs?

**Comment by 9mmfullclip** [comment] 2016-04-14 23:20
we are downgrading our codebase to 4.4r1, will let you know if things get better.

this server was running stable (without issues) with 4.4r1 for weeks.

now that we went to 4.4r2 we have the following, intermittent, nonreproducible issues:

players joining naked (not all of them)
players in jail on join
players getting their bank account, clothing, etc wiped (their players table entry gets reset as it shows, vehicles and houses and containers remain)

sometimes there is an error message like above, sometimes not even the slightest log.

this is all very disturbing for our players and leads to a lot of support issues.

however, we are a small server with around 10 regulars and 20 players max, so it can be managed with a lot of humour. we by now are used to telling people in the game that the finance institute managing the ATM has just moved from windows 95 to windows 98 which is causing headache in the banking app because its still based on MS-DOS. our users are very friendly,-they understand our pain and then take their support money with a smile on their face because we do not lose our humour in the face of these issues.

first we thought its a rogue database backup script that locked the tables at an 'inconvenient' time.
but after disabling the database backup script job the problems remain.

lets see how 4.4r1 goes.

**Comment by 9mmfullclip** [comment] 2016-04-15 00:16
btw, this is from our production db:

```
xoxo@glhf:~$ echo 'select uid,playtime from players;' | make mysql
uid     playtime
22      "[<null>,<null>,scalar Na
23      "[]"
25      "[]"
26      "[]"
27      "[0,338,283]"
28      "[0,0,13]"
29      "[0,0,1]"
30      "[scalar NaN]"
31      "[0,0,2]"
32      "[<null>,<null>,scalar Na
33      "[0,0,1]"
34      "[scalar NaN]"
35      "[0,0,816]"
36      "[0,0,47]"
37      "[]"
38      "[0,0,3]"
39      "[]"
40      "[0,295,39]"
41      "[]"
42      "[<null>,<null>,scalar Na
43      "[0,0,0]"
44      "[<null>,<null>,scalar Na
45      "[<null>,<null>,scalar Na
46      "[0,0,10]"
47      "[<null>,<null>,scalar Na
48      "[<null>,<null>,scalar Na
49      "[141]"
50      "[]"
51      "[<null>,<null>,scalar Na
52      "[scalar NaN]"
53      "[0,0,7]"
54      "[]"
55      "[<null>,<null>,scalar Na
56      "[0,0,62]"
57      "[]"
58      "[<null>,<null>,scalar Na
59      "[<null>,<null>,scalar Na
60      "[0,0,18]"
61      "[<null>,<null>,scalar Na
62      "[0,0,5]"
63      "[<null>,<null>,scalar Na
64      "[]"
65      "[600,0,2]"
66      "[0,0,64]"
67      "[0,0,11]"
68      "[<null>,<null>,scalar Na
69      "[]"
70      "[103]"
71      "[170]"
72      "[<null>,<null>,scalar Na
73      "[]"
75      "[<null>,<null>,scalar Na
76      "[]"
77      "[0,0,344]"
78      "[<null>,<null>,10]"
79      "[<null>,<null>,46]"
80      "[0,0,63]"
81      "[0,0,11]"
82      "[<null>,<null>,10]"
83      "[0,0,74]"
84      "[<null>,<null>,3]"
85      "[0,0,0]"
86      "[]"
87      "[<null>,<null>,10]"
88      "[]"
89      "[]"
90      "[]"
```

**Comment by 9mmfullclip** [comment] 2016-04-15 00:19
This is how i will "fix" this table column now after removing all the playtime logic in life_server:

```
mysql> update players set playtime='"[]"';
mysql> select uid,playtime from players limit 10;
+-----+----------+
| uid | playtime |
+-----+----------+
|  22 | "[]"     |
|  23 | "[]"     |
|  25 | "[]"     |
|  26 | "[]"     |
|  27 | "[]"     |
|  28 | "[]"     |
|  29 | "[]"     |
|  30 | "[]"     |
|  31 | "[]"     |
|  32 | "[]"     |
+-----+----------+
10 rows in set (0.00 sec)
```

**Comment by 9mmfullclip** [comment] 2016-04-15 00:45
for docs purposes: 
```
 2:29:35 Error in expression <t pushBack [_uid, _new];
};
_new = _new select 1;
[_uid, _new] call TON_fnc_setP>
 2:29:35   Error position: <select 1;
[_uid, _new] call TON_fnc_setP>
 2:29:35   Error Zero divisor
 2:29:35 File life_server\Functions\MySQL\fn_queryRequest.sqf, line 158
 2:30:19 Client: Remote object 6:0 not found
 2:30:20 Warning: Cleanup player - person 2:2127 not found
```

**Comment by 9mmfullclip** [comment] 2016-04-15 01:51
@Heavybob disabled playtime as in 'removed the logic from life_server mysql functions'. the database columns for playtime are numb now, they will not be written or read from them any more. if the problem goes away then we know where to look. if not i can add the code again...
https://github.com/ALTISLIFERPG-XOREAXEAX-DE/Altis/tree/master/life_server/Functions/MySQL

**Comment by tkcjesse** [comment] 2016-04-15 12:00
Yeah, i completely removed the playtime stuff because I too was having issues with it when i setup a friends server. @9mmfullclip, i see you closed this. Did yoi figure out the issue?

**Comment by NiiRoZz** [comment] 2016-04-15 12:20
You use HC ?

**Comment by 9mmfullclip** [comment] 2016-04-15 13:58
nope, i do not use HC. so far nobody got nulled out yet.

**Comment by 9mmfullclip** [comment] 2016-04-15 13:58
@tkcjesse i did not figure out the root cause (i am not a coder), i just operate the server and can edit/remove code from files.

**Comment by tkcjesse** [comment] 2016-04-15 14:01
Yeah, I can't be bothered figuring out what the issue is. All I know is I had the same one lol. I yanked it, did something simpler...

**Comment by DardoTheMaster** [comment] 2016-04-15 16:45
Would you mind posting a dump of the database structure?

**Comment by Heavybob** [comment] 2016-04-15 16:46
Would like to see extdb logs

**Comment by Felix2** [comment] 2016-04-17 10:58
So apparently it isn't stable at all?

**Comment by Liam0** [comment] 2016-04-17 11:43
@Felix2 i haven't had this before and with this amount of info about the issue there is no way we can even start troubleshooting it. @9mmfullclip do you have any custom changes to your files?

**Comment by Liam0** [comment] 2016-04-18 07:01
Closing, if more info about this comes up please post a detailed description and any related logs, extdb, rpt.

**Closed by Liam0** 2016-04-18 07:01 UTC
