### ISSUE TITLE
Open Vehicle Inventory

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#19] opened 2016-01-17 21:44 UTC
So now you can apparently open vehicle inventory when locked. Since inventoryOpened.sqf wasn't changed I'm assuming it's from a vehicle change? Not quite sure. Just wanted to document this... I'll look into it a bit.

**Comment by danielstuart14** [comment] 2016-01-17 22:05
Trunk or arma inventory?

**Comment by tkcjesse** [comment] 2016-01-17 22:05
@danielstuart14 Arma Inventory

**Comment by Heavybob** [comment] 2016-01-17 22:13
Will check when I start testing the latest build. Gotta test persistent trunk inv.

**Comment by tkcjesse** [comment] 2016-01-17 22:57
Using the current build both Arma and Trunk are now accessible when locked.

**Comment by sargken** [comment] 2016-01-17 22:58
@tkcjesse There are some errors with the currently build so standby.

**Comment by crackhead** [comment] 2016-01-17 23:21
https://github.com/crackhead/Altis/commit/b6ea08561f14898335c4b851fc6798909da4ebd3

**Comment by danielstuart14** [comment] 2016-01-18 01:12
Thx @crackhead

**Comment by danielstuart14** [comment] 2016-01-18 01:13
fixed now?

**Comment by tkcjesse** [comment] 2016-01-18 02:30
@danielstuart14 Haven't tested it yet. I would assume so.

**Comment by tkcjesse** [comment] 2016-01-19 03:39
@danielstuart14 Yeah, this is still an issue... Not sure why people are not testing their commits or referencing wrong issues..  :/

**Comment by Heavybob** [comment] 2016-01-19 06:31
This isn't regarding persistent inventory as it isn't apart of the master build as code was reverted. 
Please dump an rpt log of this issue and re-describe what the problem is.

**Comment by danielstuart14** [comment] 2016-01-19 06:32
It just opens the vehicle inventory, even when it is locked. 
My pull-request should fix it.

**Comment by tkcjesse** [comment] 2016-01-19 06:33
Yeah... It's   
1. Look at locked vehicle
2. Hit "i"

or 

1. Look at locked vehicle
2. Hit "T"

**Closed** 2016-01-19 09:16 UTC
Labels: bug
